sudo: required
language: node_js
node_js:
  - "4.3.2"
services:
  - docker
before_script:
  - docker pull dwmkerr/dynamodb
  - docker run -d -p 8000:8000 dwmkerr/dynamodb
  - sleep 2
  - ./build.sh
addons:
  hosts:
    - dynamodb-local
